# Generated by Django 2.1.8 on 2019-08-09 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locally', '0003_auto_20190810_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='joboffer_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
