# Generated by Django 2.1.8 on 2019-08-09 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locally', '0004_auto_20190810_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_buy',
            name='cbuy',
        ),
        migrations.AddField(
            model_name='comment_buy',
            name='buy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_buys', to='locally.Buy'),
        ),
        migrations.AddField(
            model_name='comment_buy',
            name='comment_contents',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
