# Generated by Django 2.1.8 on 2019-08-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locally', '0005_auto_20190810_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_buy',
            name='comment_contents',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
