# Generated by Django 2.1.8 on 2019-08-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locally', '0006_auto_20190810_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_buy',
            name='comment_contents',
            field=models.CharField(max_length=20),
        ),
    ]
